# -*- coding: utf-8 -*-
"""productReviewAnalyser

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SWSuxMzRnFktPCz8kTuPs5DaDfkowzjP
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

from transformers import pipeline
#load sentimental analysis mode
sentiment = pipeline("sentiment-analysis")

#load sentimental analysis mode
sentiment = pipeline("sentiment-analysis")

reviews = """ the laptopstarts quickly and works smoothly for daily tasks.
the screen quality is clear and good for watching videos.
battery backup is average and needs charging often.
the fan makes noise when many apps are running.
overall,it is a good laptop for students but not for gaming.
"""

# split review into sentences
sentences = reviews.split(".")

pros = []
cons = []

for s in sentences:
    s = s.strip()
    if s == "":
        continue

    result = sentiment(s)[0]
    if result["label"] == "POSITIVE":
      pros.append(s)

    elif result["label"] == "NEGATIVE": # Corrected typo from NEGITIVE to NEGATIVE
      cons.append(s)

# take only 2 pros and 2 cons
pros = pros[:2]
cons = cons[:2]

#create table
df = pd.DataFrame({
    "Pros": pros,
    "Cons": cons
})
df