# -*- coding: utf-8 -*-
"""sentence similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jvRyKL3nKkP94z046BYW3dWF26RQW65H
"""

!pip install transformers torch

from transformers import pipeline
generator = pipeline(
    "text-generation",
    model = "gpt2"
)
prompt = "Artificial Intelligence in finance will"
result = generator(prompt,max_length = 50,num_return_sequences = 1)
print("AI Generated text:")
print(result[0]['generated_text'])

!pip install sentence-transformers

from torch import embedding
from sentence_transformers  import SentenceTransformer,util
model = SentenceTransformer('all-MiniLM-L6-v2')
text1 = input("Enter Text 1: ")
text2 = input("Enter Text 2: ")
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)
similarity = util.cos_sim(embedding1,embedding2)
print("\nSimilarity score:",round(float(similarity), 2))
if similarity > 0.75:
  print("Similarity Level : High")
elif similarity > 0.4:
  print("Similarity Level : Medium")
else :
  print("Similarity Level : Low")