# -*- coding: utf-8 -*-
"""TIMETABLE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4iXOM1UMICWfbfQk6VL17ejdCROuGjb
"""

import pandas as pd
import random

print("TIMETABLE GENERATION\n")
subjects_input=input("enter subjects(coma seperated):")
days_input=input("enter days(coma seperated):")
periods_per_day=int(input("enter number of periods per day:"))
subjects=[s.strip() for s in subjects_input.split(',') if s.strip()]
days = [d.strip() for d in days_input.split(',') if d.strip()]
if len(subjects) == 0 or len(days) == 0 or periods_per_day <= 0:
   print("Invalid input. Please try again.")
else:
     timetable = {}
     for day in days:
         timetable[day] = random.choices(subjects,k=periods_per_day)
     df =pd.DataFrame(timetable)
     df.index ={f"Period {i+1}" for i in range(periods_per_day)}
     print("\nTimetable Generated Successfully\n")
     display(df)
     df.to_csv("timetable.csv")
     print("\nTimetable saved as timetable.csv")

import pandas as pd
from datetime import datetime

print("MEETING GENERATOR\n")
meeting_title = input("Enter meeting title:")
date =input("Enter meeting date (DD-MM-YYYY): ")
time = input("Enter meeting time: ")
participants = input("Enter participants (comma separated): ")
agenda = input("Enter agenda points(coma seperated): ")
decisions = input("Enter decisions(coma seperated): ")
action_items = input("Enter action items(coma seperated): ")
prepared_by = input("Enter prepared by: ")
participants_list =[p.strip() for p in participants.split(',') if p.strip()]
agenda_list = [a.strip() for a in agenda.split(',') if a.strip()]
decisions_list = [d.strip() for d in decisions.split(',') if d.strip()]
action_items_list = [a.strip() for a in action_items.split(',') if a.strip()]
minutes = {
    "Meeting Title": meeting_title,
    "Date": date,
    "Time": time,
    "Participants":", ".join(participants_list),
    "Agenda": "; ".join(agenda_list),
    "Decisions": "; ".join(decisions_list),
    "Action Items": "; ".join(action_items_list),\
    "Prepared By": prepared_by,
    "Generated on": datetime.now().strftime("%Y-%m-%d %H:%M:%S")

}
df =pd.DataFrame(list(minutes.items()),columns=["Field","Value"])
print("\n Meeting minutes Generated successfully\n")
display(df)
df.to_csv("meeting_minutes.csv", index=False)
print("\n File saved as meeting_minutes.csv")